# Generated by Django 6.1.1 on 2026-09-13 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Fazenda')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Nome do Proprietário')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True, verbose_name='ID/MAC do Sensor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.farm', verbose_name='Fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('dpv_kpa', models.FloatField(verbose_name='DPV (kPa)')),
                ('humidity', models.FloatField(verbose_name='Umidade (%)')),
                ('temperature', models.FloatField(verbose_name='Temperatura (°C)')),
                ('battery', models.FloatField(verbose_name='Bateria (%)')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.sensor', verbose_name='Sensor')),
            ],
        ),
    ]
