# Generated by Django 6.1.1 on 2026-09-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_sensor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.farm', verbose_name='Fazenda'),
        ),
    ]
