# Generated by Django 6.1.1 on 2026-09-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_reading_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.farm', verbose_name='Fazenda'),
        ),
    ]
