# Generated by Django 6.1.1 on 2026-09-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_reading_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50, unique=True, verbose_name='MAC Address / ID Físico')),
                ('is_used', models.BooleanField(default=False, verbose_name='Já está em uso?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
