# Generated by Django 6.1.1 on 2026-09-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_authorizeddevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_id',
            new_name='mac_address',
        ),
    ]
