# Generated by Django 6.1.1 on 2026-09-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_sensor_id_sensor_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=50, verbose_name='ID/MAC do Sensor'),
        ),
    ]
